# Generated by Django 5.0.6 on 2024-06-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="projects",
            field=models.TextField(default=12, max_length=1000),
            preserve_default=False,
        ),
    ]
