# Generated by Django 5.0.6 on 2024-06-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0002_profile_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
